name: powerflow
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python >= 3.0
  - pip
  - numpy>=1.22.4
  - pandas>=1.4.2
  - matplotlib<=3.4.3
  - scipy>=1.8.0
  - tqdm>=4.64.0
  - numba>=0.53
  - networkx>=2.7.1
  - seaborn>=0.11.2
  - pandapower>=2.8.0
  - mkl>=2022.1.0
  - psutil>=5.9.4
  - pip:
      - jupyterlab
#      - scikit-umfpack
